---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/6/13 17:44
---
function GetNearestFiltered(from, ents, isValidFunc)
    PROFILE("GetNearestFiltered")

    local bestDist, bestEnt

    for _, ent in ipairs(ents) do

        if isValidFunc == nil or isValidFunc(ent) then

            local dist = GetDistanceToTouch( from, ent )
            
            --What if functions upon bugged?   (EG: bot pickup weapon returns a unreachable amount while its pretty close [maybe its due to pathfinding upon a "un-perfect polished" map]) 
            local srcOrigin = from.GetOrigin and from:GetOrigin() or from  --pos or entity
            local targetOrigin = ent:GetOrigin()
            local straightDistanceXZ = (srcOrigin - targetOrigin):GetLengthXZ()
            if straightDistanceXZ < 5 then      --Fallback
                dist = straightDistanceXZ
            end
            
            if bestDist == nil or dist < bestDist then
                bestDist = dist
                bestEnt = ent
            end

        end

    end

    return bestDist, bestEnt

end