---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/2/10 22:34
---

local baseGetDepthForExploreLocation = LocationGraph.GetDepthForExploreLocation
function LocationGraph:GetDepthForExploreLocation(sourceLocationName, toLocationName)
    return baseGetDepthForExploreLocation(self,sourceLocationName,toLocationName) or -1
end

local kFallbackGatewayDistTable = {
    distance = 999*999,
     enterGatePos = Vector(0,0,0), -- the gateway pos on the starting location we used
     exitGatePos = Vector(999,0,999), -- the gateway pos on the end location we used
}

local baseGetGatewayDistance = LocationGraph.GetGatewayDistance
function LocationGraph:GetGatewayDistance(botLocationName, targetLocationName)
    return baseGetGatewayDistance(self,botLocationName,targetLocationName) or kFallbackGatewayDistTable
end