---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by letsb.
--- DateTime: 2026/2/26 1:24
---

if Locale.kTranslateMessage then
    Locale.kTranslateMessage["BOOMBOX_TITLE"]="车载音响"
    Locale.kTranslateMessage["BOOMBOX_CUSTOM"]="定制"
    Locale.kTranslateMessage["BOOMBOX_OST"]="原声"
    Locale.kTranslateMessage["BOOMBOX_SONG"]="英语"
    Locale.kTranslateMessage["BOOMBOX_TWO"]="日语"
    Locale.kTranslateMessage["BOOMBOX_CN"]="中文"
    Locale.kTranslateMessage["BOOMBOX_VOLUME"]="音量校正[%s]"
    Locale.kTranslateMessage["BOOMBOX_STOP"]="停止"
    Locale.kTranslateMessage["BOOMBOX_RANDOM"]="随机"
end

if Locale.kLocales then
    Locale.kLocales["BOOMBOX_TITLE"]="BoomBox"
    Locale.kLocales["BOOMBOX_OST"]="OST"
    Locale.kLocales["BOOMBOX_SONG"]="EN"
    Locale.kLocales["BOOMBOX_CUSTOM"]="Custom"
    Locale.kLocales["BOOMBOX_TWO"]="JP"
    Locale.kLocales["BOOMBOX_CN"]="CN"
    Locale.kLocales["BOOMBOX_VOLUME"]="Volume[%s]"
    Locale.kLocales["BOOMBOX_STOP"]="Stop"
    Locale.kLocales["BOOMBOX_RANDOM"]="Random"
end
