--Loading
kTranslateMessage["LOADING_VAC"] = "服务器受到<VAC>保护.\n作弊将导致永久封禁."
kTranslateMessage["LOADING_MODLIST"] = "正在运行的MOD:\n"

kTranslateMessage["STARTING_LOCAL_SERVER"]="开启本地服务器"
kTranslateMessage["ATTEMPTING_CONNECTION"]="尝试建立连接"
kTranslateMessage["AUTHENTICATING"]="校验中"
kTranslateMessage["LOADING_2"]="加载中"
kTranslateMessage["PRECACHING"]="预缓存资源"
kTranslateMessage["INITIALIZING_GAME"]="初始化游戏"
kTranslateMessage["LOADING_MAP"]="加载地图"
kTranslateMessage["LOADING_ASSETS"]="读取必要资源"
kTranslateMessage["DOWNLOADING_MODS"]="正在更新MOD"
kTranslateMessage["CONNECTING"]="正在连接"
kTranslateMessage["LOADING_SHADERS"]="加载着色器"


kTranslateMessage["LOADING_TIP"] = "提示:"
kTranslateMessage["LOADING_TIP_ABILITIES"] = "部分建筑有被动能力,例如 陆战队的雷达 及 卡拉异形的回气塔."
kTranslateMessage["LOADING_TIP_BEARARMS"] = "按下[BIND_Drop]捡起死亡队员的武器. 动作要快 - 他们很快就会消失."
kTranslateMessage["LOADING_TIP_COMMANDER_SPEAKING"] = "队伍的指挥官信息与名字将显示为黄色."
kTranslateMessage["LOADING_TIP_EVOLVE"] = "作为卡拉异形 按下[BIND_Buy]获取升级及演化为高级单位."
kTranslateMessage["LOADING_TIP_EXPLORE"] = "开一个独立服务器将更多的了解物竞天择2,但最快的方法是加群问好群友."
kTranslateMessage["LOADING_TIP_F4"] = "按下[BIND_ReadyRoom]回到预备室以加入战局."
kTranslateMessage["LOADING_TIP_FF"] = "目前没有友军伤害. 但是你自己可以通过榴弹及地雷自杀."
kTranslateMessage["LOADING_TIP_GOODCOMM"] = "作为指挥官,你可以给地面部队提供武器以及高级异形乱."
kTranslateMessage["LOADING_TIP_GOTOALERT"] = "作为指挥官,按下[BIND_Jump]前往警报点."
kTranslateMessage["LOADING_TIP_INFESTATION"] = "卡拉异形菌毯通过母巢向外延申. 如果被打断,前端的菌毯将逐渐掉血直至死亡,建筑物也随后消亡."
kTranslateMessage["LOADING_TIP_MAP"] = "按下[BIND_ShowMap]打开地图,包含很多有用信息."
kTranslateMessage["LOADING_TIP_MODS"] = "物竞天择2 完全插件定制化. 目前你进入的服务器以安装<社区强制汉化>插件,由@StriteR.提供以解决官方的汉化问题."
kTranslateMessage["LOADING_TIP_MUTE"] = "对于让你糟心的玩家,按下[BIND_Scoreboard]打开积分面板,并左键此人可独立禁言/禁麦他."
kTranslateMessage["LOADING_TIP_NEXT"] = "按下 SPACE 显示下一条提示"
kTranslateMessage["LOADING_TIP_NOIINTEAM"] = "通过[BIND_VoiceChat]于你的队友沟通交流. 沟通更流畅的队伍迎面也越大!"
kTranslateMessage["LOADING_TIP_POWER"] = "陆战队的建筑需要电源. 如果电力节点被摧毁,区域内的建筑将失去电力."
kTranslateMessage["LOADING_TIP_PRIORITY"] = "将你的目标优先级排序. 摧毁电源及菌毯很重要,但是摧毁一个资源塔将给对方带来更长远的伤害."
kTranslateMessage["LOADING_TIP_RAMBO"] = "人多力量大-不要当独狼!"
kTranslateMessage["LOADING_TIP_REQ_MENU"] = "作为陆战队员,按下[BIND_RequestMenu]要求指挥官给予你弹药及血包."
kTranslateMessage["LOADING_TIP_RESOURCES"] = "建造资源塔以提供玩家/团队资源."
kTranslateMessage["LOADING_TIP_ROOKIES"] = "新兵玩家<名字/分段>将以绿色显示. 请对他们好一点."
kTranslateMessage["LOADING_TIP_SAYINGS_MENU"] = "按下[BIND_ToggleSayings]以进行怪话的说."
kTranslateMessage["LOADING_TIP_SCOREBOARD"] = "按下[BIND_Scoreboard]打开计分板,包含所有玩家的各项数据."
kTranslateMessage["LOADING_TIP_SPAWN"] = "陆战队从步兵传送器重生,卡拉异形从卵里孵化重生."
kTranslateMessage["LOADING_TIP_SPEEDYGONZALES"] = "跑步将使你更快速抵达目标,但请记住,发出的声音也比走路及蹲伏更大."
kTranslateMessage["LOADING_TIP_SUPPORT"] = "支援单位同样也很重要! 一个放建筑的Gorge以及带焊枪的陆战队将对团队有巨大帮助."
kTranslateMessage["LOADING_TIP_VENTS"] = "卡拉异形通过管道快速移动及包围."
kTranslateMessage["LOADING_TIP_WALLRUN"] = "作为Skulk,不要直直的冲向陆战队,贴在天花板上伏击他们."

kTranslateMessage["DOWNLOAD_COMPLETE"] = "下载成功!"
kTranslateMessage["DOWNLOAD_FAILED"] = "下载失败!"
kTranslateMessage["DOWNLOADING_REPLAY"] = "下载回放中..."

kTranslateMessage["PLAY"] = "开始游戏"
kTranslateMessage["JOIN"] = "加入"
kTranslateMessage["BACK"] = "返回"
kTranslateMessage["CANCEL"] = "取消"
kTranslateMessage["DISABLED"]="禁用"
kTranslateMessage["NO"] = "否"
kTranslateMessage["YES"] = "是"
--MENU TAB
kTranslateMessage["VOTE"] = "投票"
kTranslateMessage["OPTIONS"] = "选项"
kTranslateMessage["CREDITS"] = "制作团队"
kTranslateMessage["SKINS"] = "皮肤"
kTranslateMessage["MENU_APPLY"] = "应用"

kTranslateMessage["VOTE_CALL_VOTE"] = "发起投票"
kTranslateMessage["VOTE_KICK_PLAYER"] = "玩家处理 - [踢出]"
kTranslateMessage["VOTE_CHANGE_MAP"] = "换图提名"
kTranslateMessage["VOTE_RESET_GAME"] = "重置游戏"
kTranslateMessage["VOTE_RANDOMIZE_RR"] = "随机预备室玩家"
kTranslateMessage["VOTE_FORCE_EVEN_TEAMS"] = "洗牌分队"
kTranslateMessage["VOTE_ADD_COMMANDER_BOTS"] = "添加电脑指挥官"

kTranslateMessage["MENU_LABEL_BETA"] = "测试"
kTranslateMessage["MENU_LABEL_BETA2"] = "测试 v2"
kTranslateMessage["MENU_LABEL_BETA3"] = "测试 v3"

kTranslateMessage["SERVERBROWSER_CREATE_ADD_BOTS"] = "添加电脑"
kTranslateMessage["SERVERBROWSER_CREATE_GAME_MODE"] = "游戏模式"
kTranslateMessage["SERVERBROWSER_CREATE_PASSWORD"] = "密码 [可选]"
kTranslateMessage["SERVERBROWSER_CREATE_PLAYER_LIMIT"] = "玩家数量"
kTranslateMessage["SERVERBROWSER_CREATE_PORT"] = "端口 [可选]"
kTranslateMessage["SERVERBROWSER_CREATE_LOAD_HOTFIXM_MODS"] = "加载热更新补丁"
kTranslateMessage["START_SERVER"] = "开启服务器"

kTranslateMessage["PLAY_MENU_QUICK_PLAY"] = "快速加入"
kTranslateMessage["PLAY_MENU_QUICK_PLAY_DESCRIPTION"] = "自动为您选择合适的服务器加入!"

-- JOIN /EXIT
kTranslateMessage["QUIT_CAPS"] = "退出"
kTranslateMessage["MENU_GO_TO_READY_ROOM"] = "回到预备室"
kTranslateMessage["LEAVE_SERVER"] = "离开服务器"
kTranslateMessage["QUIT_GAME"] = "退出游戏"

kTranslateMessage["MENU_MATCHED_PLAY"] = "匹配模式"
kTranslateMessage["MENU_SERVER_BROWSER"] = "社区服务器"
kTranslateMessage["MENU_CHALLENGES"] = "挑战"
kTranslateMessage["MENU_TRAINING"] = "训练"
kTranslateMessage["MENU_START_LISTEN_SERVER"] = "开启服务器"

-- kTranslateMessage["SERVERBROWSER_BLOCKED_SERVERS"] = "隐藏的服务器"
-- kTranslateMessage["SERVERBROWSER_BLOCKED_SERVERS_HIDE"] = "隐藏"
-- kTranslateMessage["SERVERBROWSER_BLOCKED_SERVERS_SHOW"] = "显示"
-- kTranslateMessage["SERVERBROWSER_BLOCKED_SERVERS_LIST_ALL"] = "EXCLUSIVE"
-- kTranslateMessage["SERVERBROWSER_BLOCKED_SERVERS_TOOLTIP"] = "Blocked servers are not considered for Quick Play.  Choose here whether to show, hide, or show exclusively servers that you have blocked."
-- kTranslateMessage["SERVERBROWSER_BLOCKED_SERVERS_SORT_TOOLTIP"] = "Sort servers by whether or not they are blocked.  Blocked servers are not considered for Quick Play."
-- kTranslateMessage["SERVERBROWSER_BLOCKED_TOOLTIP_1"] = "Unblock this server"
-- kTranslateMessage["SERVERBROWSER_BLOCKED_TOOLTIP_2"] = "Block this server.  Blocked servers are not considered for Quick Play, and may be hidden from the server browser."
kTranslateMessage["PLAYER_PROFILE"] = "玩家信息/自定义"
kTranslateMessage["NEWS"] = "新消息"
kTranslateMessage["CHANGELOG_TITLE"] = "版本补丁"

--Customizations
kTranslateMessage["CUSTOMIZE_MENU_BADGES"] = "自定义徽章"
kTranslateMessage["FRIENDS"] = "好友"
kTranslateMessage["FRIEND_STATE_OFFLINE"] = "离线"
kTranslateMessage["FRIEND_STATE_ONLINE"] = "在线"
kTranslateMessage["FRIEND_STATE_BUSY"] = "忙碌中"
kTranslateMessage["FRIEND_STATE_AWAY"] = "离开"
kTranslateMessage["FRIEND_STATE_SNOOZE"] = "打盹"
kTranslateMessage["FRIEND_STATE_LOOKING_TRADE"] = "寻找交易"
kTranslateMessage["FRIEND_STATE_LOOKING_PLAY"] = "寻找游戏"
kTranslateMessage["FRIEND_STATE_IN_GAME"] = "游戏中"
kTranslateMessage["FRIEND_INVITE_TT"] = "邀请好友加入您当前的服务器"
kTranslateMessage["FRIEND_JOIN_TT"] = "加入好友正在游玩的服务器"
kTranslateMessage["FRIEND_JOINING_TITLE"] = "自定义"
kTranslateMessage["FRIEND_JOINING_DESC"] = "加载服务器详情"
kTranslateMessage["FRIEND_LEFT_SERVER"] = "好友不在任何服务器"
kTranslateMessage["FRIEND_PLAYING_ON"] = "正在<%s>游玩"

--Server Browser
kTranslateMessage["SERVER_PERF_BAD"] = "满载"
kTranslateMessage["SERVER_PERF_GOOD"] = "良好"
kTranslateMessage["SERVER_PERF_LOADED"] = "负载"
kTranslateMessage["SERVER_PERF_OK"] = "优良"
kTranslateMessage["SERVER_PERF_UNKNOWN"] = "未知"

kTranslateMessage["FAVORITES"] = "收藏"
kTranslateMessage["SERVERBROWSER_DETAILS_TOOLTIP"] = "显示/隐藏服务器详细信息."
kTranslateMessage["SERVERBROWSER_FAVORITES"] = "偏好的服务器"
kTranslateMessage["SERVERBROWSER_FAVORITES_SORT_TOOLTIP"] = "Sort servers by whether or not they are marked as your favorite."
kTranslateMessage["SERVERBROWSER_FAVORITE_TOOLTIP_1"] = "Remove this server from your favorites."
kTranslateMessage["SERVERBROWSER_FAVORITE_TOOLTIP_2"] = "Add this server to your favorites."
kTranslateMessage["SERVERBROWSER_FILTER_BOOTCAMP_TOOLTIP"] = "Display servers that only rookies can play on (non-rookies can still spectate if there is room)."
kTranslateMessage["SERVERBROWSER_FILTER_EMPTY"] = "隐藏 空的"
kTranslateMessage["SERVERBROWSER_FILTER_FULL"] = "隐藏 已满"
kTranslateMessage["SERVERBROWSER_FILTER_GAMEMODE_ALL"] = "所有"
kTranslateMessage["SERVERBROWSER_FILTER_GAMEMODE_OTHERS"] = "%{amount}d OTHER(S)..."
kTranslateMessage["SERVERBROWSER_FILTER_FRIENDS_ON_SERVER"] = "与朋友一起游戏"
kTranslateMessage["SERVERBROWSER_FILTER_FRIENDS_ON_SERVER_TOOLTIP"] = "Only show servers that have friends playing on them."
kTranslateMessage["SERVERBROWSER_FILTER_UNRANKED_TOOLTIP"] = "Show servers that are unranked.  Skill rating and XP are not impacted while playing on unranked servers."
kTranslateMessage["SERVERBROWSER_FILTERS"] = "过滤选项"
kTranslateMessage["SERVERBROWSER_FRIEND_TOOLTIP"] = "One or more of your Steam friends are playing on this server."
kTranslateMessage["SERVERBROWSER_GAME"] = "模式"
kTranslateMessage["SERVERBROWSER_GAME_MODE_SORT_TOOLTIP"] = "Sort servers based on the name of the gamemode being played."
kTranslateMessage["SERVERBROWSER_GAMEMODE_ALL_HIDDEN_TT"] = "No gamemodes selected!"
kTranslateMessage["SERVERBROWSER_GAMEMODE_TOOLTIP"] = "Pick a gamemode"
kTranslateMessage["SERVERBROWSER_HISTORY"] = "历史"
kTranslateMessage["SERVERBROWSER_MAP"] = "地图"
kTranslateMessage["SERVERBROWSER_MAPNAME"] = "地图名"
kTranslateMessage["SERVERBROWSER_MAXPING"] = "最大延迟"
kTranslateMessage["SERVERBROWSER_NAME"] = "名字"
kTranslateMessage["SERVERBROWSER_PASSWORD"] = "密码"
kTranslateMessage["SERVERBROWSER_PASSWORDED"] = "需要密码"
kTranslateMessage["SERVERBROWSER_PASSWORDED_FILTER_TOOLTIP"] = "Show servers that require passwords to join."
kTranslateMessage["SERVERBROWSER_PASSWORD_INCORRECT_TOOLTIP"] = "Password was incorrect."
kTranslateMessage["SERVERBROWSER_PASSWORD_MISSING_TOOLTIP"] = "Password is required for this server."
kTranslateMessage["SERVERBROWSER_PASSWORD_TOOLTIP"] = "This server requires a password to join."
kTranslateMessage["SERVERBROWSER_PASSWORD_SORT_TOOLTIP"] = "Sort servers based on whether or not they require a password to join."
kTranslateMessage["SERVERBROWSER_PERF"] = "性能:"
kTranslateMessage["SERVERBROWSER_PERF_MIN"] = "最低性能"
kTranslateMessage["SERVERBROWSER_PERF_MIN_TOOLTIP"] = "Only show servers with performance ratings better-than or equal-to this rating."
kTranslateMessage["SERVERBROWSER_PING"] = "延迟"
kTranslateMessage["SERVERBROWSER_PING_TOOLTIP"] = "Only show servers with ping lower than or equal to this value.  Ping (aka latency, lag) is how much time information takes to arrive at the server and then return to you.  Lower is better."
kTranslateMessage["SERVERBROWSER_PLAYERCOUNT"] = "正在游戏的人数:"
kTranslateMessage["SERVERBROWSER_PLAYER_SLOTS_TOOLTIP"] = "The number of player-slots in-use out of the total available player-slots."
kTranslateMessage["SERVERBROWSER_PLAYERS"] = "玩家数"
kTranslateMessage["SERVERBROWSER_PLAYERS_SEARCHING"] = "正在浏览服务器的人数:."
kTranslateMessage["SERVERBROWSER_PRIVATE"] = "私有"
kTranslateMessage["SERVERBROWSER_QUICK_PLAY_RANK_SORT_TOOLTIP"] = "Sort servers based on the ranking calculated by Quick Play."
kTranslateMessage["SERVERBROWSER_RANKEDONLY"] = "隐藏 不计分的"
kTranslateMessage["SERVERBROWSER_RANK"] = "计分"
kTranslateMessage["SERVERBROWSER_RANKED"] = "计分服"
kTranslateMessage["SERVERBROWSER_RANKED_TOOLTIP"] = "This server is ranked! It reports to the Hive stats system."
kTranslateMessage["SERVERBROWSER_RANKED_SORT_TOOLTIP"] = "Sort servers based on whether or not they are whitelisted."
kTranslateMessage["SERVERBROWSER_REFRESH"] = "刷新"
kTranslateMessage["SERVERBROWSER_ROOKIEONLY"] = "新兵营"
kTranslateMessage["SERVERBROWSER_ROOKIEONLY_TOOLTIP"] = "Only rookies are allowed to play on this server."
kTranslateMessage["SERVERBROWSER_SCORE"] = "分数"
kTranslateMessage["SERVERBROWSER_SEARCH"] = "寻找 ..."
kTranslateMessage["SERVERBROWSER_SEARCHING"] = "寻找中..."
kTranslateMessage["SERVERBROWSER_SERVERNAME"] = "服务器名"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS"] = "服务器信息"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_ADDRESS"] = "地址"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_GAME"] = "游戏模式:"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_MAP"] = "地图:"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_MODS"] = "插件:"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_PERF"] = "性能"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_PING"] = "延迟:"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_PLAYERS"] = "玩家数:"
kTranslateMessage["SERVERBROWSER_SERVER_DETAILS_SPECTATORS"] = "观战数:"
kTranslateMessage["SERVERBROWSER_SKILL_SORT_TOOLTIP"] = "Sort servers by the average player skill of those playing."
kTranslateMessage["SERVERBROWSER_SPECTATORS"] = "观战者"
kTranslateMessage["SERVERBROWSER_SPECTATOR_SLOTS_TOOLTIP"] = "The number of spectator-only player-slots used out of the total amount."
kTranslateMessage["SERVERBROWSER_SHOW_EMPTY"] = "空的"
kTranslateMessage["SERVERBROWSER_SHOW_EMPTY_TOOLTIP"] = "显示空的服务器."
kTranslateMessage["SERVERBROWSER_SHOW_FULL"] = "已满"
kTranslateMessage["SERVERBROWSER_SHOW_FULL_TOOLTIP"] = "显示已满的服务器 (预留位不加入计算)."
kTranslateMessage["SERVERBROWSER_SHOW_UNRANKED"] = "未计分"
kTranslateMessage["SERVERBROWSER_SKILL"] = "段位"
kTranslateMessage["SERVERBROWSER_TIME_PLAYED"] = "当前对局时间"
kTranslateMessage["SERVERBROWSER_UPDATE"] = "更新中..."
kTranslateMessage["SERVERBROWSER_UNRANKED_TOOLTIP"] = "服务器暂未计分!  游玩不会得到经验与段位."

--OPTIONS
kTranslateMessage["GENERAL"] = "常用"
kTranslateMessage["MENU_ADVANCED"] = "高级"
kTranslateMessage["MENU_MODS"] = "插件"
kTranslateMessage["GRAPHICS"] = "画面"
kTranslateMessage["SOUND"] = "声效"

kTranslateMessage["HIGH"] = "高"
kTranslateMessage["LOW"] = "低"
kTranslateMessage["RICH"] = "丰富"
kTranslateMessage["MINIMAL"] = "最小"

kTranslateMessage["OPTIONS_UNSAVED_CHANGES"] = "未应用的设置"
kTranslateMessage["OPTIONS_UNSAVED_CHANGES_MESSAGE"] = "有些设置还未应用,想应用他们吗?"
kTranslateMessage["OPTIONS_SAVE"] = "应用"
kTranslateMessage["OPTIONS_REVERT"] = "还原"
--General
kTranslateMessage["SHOW_HINTS"]="显示提示"
kTranslateMessage["OPTION_SHOW_HINTS"]="显示提示与教学视频"
kTranslateMessage["DAMAGE_NUMBERS"]="伤害数字"
kTranslateMessage["OPTION_DRAW_DAMAGE"]="造成伤害时显示数字"
kTranslateMessage["OPTION_PHYSICS_MULTITHREADING"]="物理多线程"
kTranslateMessage["OPTION_PHYSICS_MULTITHREADING_TOOLTIP"]="使用CPU多线程增加大型战场的帧率.\n实验性选项 - 出现问题请关闭"

kTranslateMessage["MINIMAP_ZOOM"] = "小地图校准"
kTranslateMessage["MINIMAP_ZOOM_TOOLTIP"] = "调整左上角显示的小地图大小(仅针对陆战队)."

kTranslateMessage["OPTION_PERTEAM_FOV"] = "队伍定制 FOV"
kTranslateMessage["OPTION_PERTEAM_FOV_TOOLTIP"] = "逐队伍设置FOV."

kTranslateMessage["FOV_ADJUSTMENT"] = "FOV 调整"
kTranslateMessage["FOV_ADJUSTMENT_TOOLTIP"] = "使你的视角更宽阔!"

kTranslateMessage["OPTION_FOV_MARINE"] = "边境拓荒者部队 FOV"
kTranslateMessage["OPTION_FOV_MARINE_TOOLTIP"] = "针对<边境拓荒者部队>的FOV."
kTranslateMessage["OPTION_FOV_ALIEN_TOOLTIP"] = "针对<卡拉异形>的FOV."
kTranslateMessage["OPTION_FOV_ALIEN"] = "卡拉异形 FOV"

kTranslateMessage["LANGUAGE"]="语言(正在使用强制汉化,请勿调整至中文!)"
kTranslateMessage["NS2NICKNAME"]="使用自定昵称"
kTranslateMessage["MENU_TOOLTIP_ALTERNATE_NICKNAME"] = "使用自定义名称以代替Steam名称."

kTranslateMessage["HUD_DETAIL"]="HUD细节"
kTranslateMessage["HUD_DETAIL_TOOLTIP"]="抬头显示器的UI细节"

kTranslateMessage["MENU_MUSIC"]="主菜单音乐"
kTranslateMessage["MENU_MUSIC_DEFAULT"]="默认"
kTranslateMessage["MENU_MUSIC_RANDOM"]="随机"
-- kTranslateMessage["MENU_MUSIC_ECLIPSE_REMIX"]="日食区混音"
-- kTranslateMessage["MENU_MUSIC_EXO"]="外骨骼机甲"
-- kTranslateMessage["MENU_MUSIC_BETA"]="物竞天择2测试版"
-- kTranslateMessage["MENU_MUSIC_NS1"]="物竞天择1"
-- kTranslateMessage["MENU_MUSIC_FRONTIERSMEN"]="边境拓荒者部队"

kTranslateMessage["MENU_BACKGROUND"]="主菜单背景"
kTranslateMessage["MENU_BACKGROUND_DEFAULT"]="默认背景"
kTranslateMessage["MENU_BACKGROUND_RANDOM"]="随机背景"
-- MENU_BACKGROUND_DERELICT = "Derelict"
-- MENU_BACKGROUND_ECLIPSE = "Eclipse"
-- MENU_BACKGROUND_KODIAK = "Kodiak"
-- MENU_BACKGROUND_BIODOME = "Biodome"
-- MENU_BACKGROUND_DESCENT = "Descent"
-- MENU_BACKGROUND_DOCKING = "Docking"
-- MENU_BACKGROUND_METRO = "Metro"
-- MENU_BACKGROUND_MINESHAFT = "Mineshaft"
-- MENU_BACKGROUND_ORIGIN = "Origin"
-- MENU_BACKGROUND_REFINERY = "Refinery"
-- MENU_BACKGROUND_SUMMIT = "Summit"
-- MENU_BACKGROUND_TANITH = "Tanith"
-- MENU_BACKGROUND_TRAM = "Tram"
-- MENU_BACKGROUND_VEIL = "Veil"
-- MENU_BACKGROUND_CAGED = "Caged"
-- MENU_BACKGROUND_UNEARTHED = "Unearthed"

---Controls
kTranslateMessage["CONTROLS"]="按键与操作"
kTranslateMessage["FIELD_PLAYER_BINDINGS"]="地面部队"
kTranslateMessage["INVERT_MOUSE"]="鼠标反转"
kTranslateMessage["INVERT_MOUSE_TOOLTIP"] = "反转鼠标的垂直移动."
kTranslateMessage["MOUSE_ACCELERATION"]="鼠标加速"
kTranslateMessage["MOUSE_ACCELERATION_TOOLTIP"] = "速度与鼠标移动距离挂钩.\n慢速移动更精准,快速移动大身位."
kTranslateMessage["MOUSE_SENSITIVITY"] = "鼠标灵敏度"
kTranslateMessage["MOUSE_SENSITIVITY_TOOLTIP"] = "设置鼠标灵敏度.\n*如果使用逐单位设置,这个选项将被覆盖."

kTranslateMessage["OPTION_PERTEAM_SENSITIVITY"] = "队伍鼠标灵敏度"
kTranslateMessage["OPTION_PERTEAM_SENSITIVITY_TOOLTIP"] = "不同的队伍使用不同的鼠标灵敏度."
kTranslateMessage["OPTION_MARINETEAM_SENSITIVITY"] = "边境拓荒者部队 灵敏度"
kTranslateMessage["OPTION_MARINETEAM_SENSITIVITY_TOOLTIP"] = "设置边境拓荒者部队的鼠标灵敏度."
kTranslateMessage["OPTION_ALEINTEAM_SENSITIVITY"] = "卡拉异形 灵敏度"
kTranslateMessage["OPTION_ALEINTEAM_SENSITIVITY_TOOLTIP"] = "设置卡拉异形的鼠标灵敏度."
kTranslateMessage["OPTION_PERLIFEFORM_SENSITIVITY"] = "逐单位灵敏度"
kTranslateMessage["OPTION_PERLIFEFORM_SENSITIVITY_TOOLTIP"] = "不同的单位使用不同的灵敏度."
kTranslateMessage["OPTION_SKULK_SENSITIVITY"] = "SKULK 灵敏度"
kTranslateMessage["OPTION_SKULK_SENSITIVITY_TOOLTIP"] = "设置Skulk的鼠标灵敏度."
kTranslateMessage["OPTION_GORGE_SENSITIVITY"] = "GORGE 灵敏度"
kTranslateMessage["OPTION_GORGE_SENSITIVITY_TOOLTIP"] = "设置Gorge的鼠标灵敏度."
kTranslateMessage["OPTION_LERK_SENSITIVITY"] = "LERK 灵敏度"
kTranslateMessage["OPTION_LERK_SENSITIVITY_TOOLTIP"] = "设置Lerk的鼠标灵敏度."
kTranslateMessage["OPTION_FADE_SENSITIVITY"] = "FADE 灵敏度"
kTranslateMessage["OPTION_FADE_SENSITIVITY_TOOLTIP"] = "设置Fade的鼠标灵敏度."
kTranslateMessage["OPTION_ONOS_SENSITIVITY"] = "Onos 灵敏度"
kTranslateMessage["OPTION_ONOS_SENSITIVITY_TOOLTIP"] = "设置Onos的鼠标灵敏度."

kTranslateMessage["BINDINGS"] = "按键绑定"
kTranslateMessage["OPTION_CLEAR_BIND"] = "解除绑定"
kTranslateMessage["OPTION_RESET_BIND"] = "重置至默认设置"

kTranslateMessage["MOVEMENT"] = "移动"
kTranslateMessage["BINDINGS_JUMP"] = "跳跃"
kTranslateMessage["BINDINGS_MOVE_BACKWARD"] = "后退"
kTranslateMessage["BINDINGS_MOVE_FORWARD"] = "前进"
kTranslateMessage["BINDINGS_MOVE_LEFT"] = "左侧移"
kTranslateMessage["BINDINGS_MOVE_RIGHT"] = "右侧移"
kTranslateMessage["BINDINGS_MOVEMENT_SPECIAL"] = "特殊移动"
kTranslateMessage["BINDINGS_MOVEMENT_SPECIAL_TOOLTIP"] = "使用当前单位的特殊移动,陆战队为跑步,Skulk则是静步,以此类推."
kTranslateMessage["BINDINGS_CROUCH"] = "蹲伏"

kTranslateMessage["COMBAT_AND_INTERACTION"] = "战斗与交互"

kTranslateMessage["BINDINGS_PRIMARY_ATTACK"] = "主攻击键"
kTranslateMessage["BINDINGS_SECONDARY_ATTACK"] = "副攻击键"
kTranslateMessage["BINDINGS_TERTIARY_ATTACK"] = "次攻击键."
kTranslateMessage["BINDINGS_TERTIARY_ATTACK_TT"] = "目前只用于快速投掷手雷."
kTranslateMessage["BINDINGS_RELOAD"] = "装填"
kTranslateMessage["BINDINGS_USE"] = "使用"
kTranslateMessage["BINDINGS_FLASHLIGHT"] = "切换手电/卡拉视觉"
kTranslateMessage["BINDINGS_DROP_WEAPON_/_EJECT"] = "丢弃武器/机甲弹出"
kTranslateMessage["BINDINGS_NEXT_WEAPON"] = "下一个武器"
kTranslateMessage["BINDINGS_PREVIOUS_WEAPON"] = "上一个武器"
kTranslateMessage["BINDINGS_WEAPON_#1"] = "武器#1"
kTranslateMessage["BINDINGS_WEAPON_#2"] = "武器#2"
kTranslateMessage["BINDINGS_WEAPON_#3"] = "武器#3"
kTranslateMessage["BINDINGS_WEAPON_#4"] = "武器#4"
kTranslateMessage["BINDINGS_WEAPON_#5"] = "武器#5"
kTranslateMessage["BINDINGS_QUICK_SWITCH"] = "切换至上次使用的武器"
kTranslateMessage["BINDINGS_EVOLVE_LAST_UPGRADES"] = "进行与上次同样的进化"
kTranslateMessage["BINDINGS_BUY/EVOLVE_MENU"] = "购买/演化菜单"

kTranslateMessage["COMMUNICATION_AND_INFORMATION"] = "信息与交流"
kTranslateMessage["BINDINGS_REQUEST_AMMO_/_ENZYME"] = "请求弹药/狂暴云"
kTranslateMessage["BINDINGS_REQUEST_HEALING_/_MEDPACK"] = "请求治疗/医疗包"
kTranslateMessage["BINDINGS_REQUEST_ORDER"] = "请求命令"
kTranslateMessage["BINDINGS_REQUEST_STRUCTURE"] = "请求建筑"
kTranslateMessage["BINDINGS_REQUEST_WELD"] = "请求维修"
kTranslateMessage["BINDINGS_TOGGLE_MINIMAP_NAMES"] = "切换小地图名称显示"
kTranslateMessage["BINDINGS_TAUNT"] = "嘲讽"

kTranslateMessage["BINDINGS_VOICE_ACKOWLEDGED"] = "了解/明白"
kTranslateMessage["BINDINGS_VOICE_COVERING"] = "(陆战队) 掩护中"
kTranslateMessage["BINDINGS_VOICE_FOLLOW"] = "(陆战队) 跟着我"
kTranslateMessage["BINDINGS_VOICE_HOSTILES"] = "(陆战队) 发现敌方单位"
kTranslateMessage["BINDINGS_VOICEOVER_MENU"] = "语音指令轮盘"
kTranslateMessage["BINDINGS_PUBLIC_CHAT"] = "全局打字交流"
kTranslateMessage["BINDINGS_EVERYBODY_TEXT_CHAT"] = "全局打字交流"
kTranslateMessage["BINDINGS_TEAM_CHAT"] = "队伍打字交流"
kTranslateMessage["BINDINGS_PUSH_TO_TALK"] = "开启麦克风"
kTranslateMessage["BINDINGS_SCOREBOARD"] = "计分板"
kTranslateMessage["BINDINGS_SHOW_MAP"] = "查看地图"
kTranslateMessage["BINDINGS_SHOW_TECH_TREE"] = "查看科技树"
kTranslateMessage["BINDINGS_PING_LOCATION"] = "标记地点"

kTranslateMessage["MISCELLANEOUS"] = "杂项"
kTranslateMessage["BINDINGS_TOGGLE_CONSOLE"] = "切换控制台"
kTranslateMessage["JOIN_ALIENS"]="加入异形"
kTranslateMessage["JOIN_MARINES"]="加入陆战队"
kTranslateMessage["JOIN_SPECTATE"]="观战"
kTranslateMessage["BINDINGS_GO_TO_READY_ROOM"] = "加入预备室"
kTranslateMessage["BINDINGS_VOTE_YES"] = "投票-同意"
kTranslateMessage["BINDINGS_VOTE_NO"] = "投票-否决"
kTranslateMessage["HELP_SCREEN"]="帮助界面"
kTranslateMessage["PROFILE_PAUSE"] = "切换性能监控"
kTranslateMessage["PROFILE_PAUSE_TOOLTIP"] = "开启/关闭 性能帧收集(仅当\"profile\" 指令开启时)"

kTranslateMessage["COMMANDER_BINDINGS"]="指挥官"
kTranslateMessage["COMBINDINGS_SHOW_MAP"] = "查看地图"
kTranslateMessage["COMMANDER_GRID"]="指挥按键绑定"
kTranslateMessage["COMBINDINGS_GO_TO_PREVIOUS_LOCATION"] = "前往上个地点"
kTranslateMessage["COMBINDINGS_GO_TO_ALERT"] = "前往警报点"
kTranslateMessage["COMBINDINGS_GRID_SPOT_10_(DEFAULT_G)"] = "按键 10 (默认 G)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_11_(DEFAULT_V)"] = "按键 11 (默认 V)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_1_(DEFAULT_Q)"] = "按键 1 (默认 Q)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_2_(DEFAULT_W)"] = "按键 2 (默认 W)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_3_(DEFAULT_E)"] = "按键 3 (默认 E)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_4_(DEFAULT_A)"] = "按键 4 (默认 A)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_5_(DEFAULT_S)"] = "按键 5 (默认 S)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_6_(DEFAULT_D)"] = "按键 6 (默认 D)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_7_(DEFAULT_F)"] = "按键 7 (默认 F)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_8_(DEFAULT_Z)"] = "按键 8 (默认 Z)"
kTranslateMessage["COMBINDINGS_GRID_SPOT_9_(DEFAULT_X)"] = "按键 9 (默认 X)"
kTranslateMessage["COMBINDINGS_TOGGLE_HEALTHBARS"] = "显示友方建筑血条"
kTranslateMessage["COMBINDINGS_MOVEMENT_SPECIAL"] = "移动覆盖"
kTranslateMessage["COMBINDINGS_MOVEMENT_SPECIAL_TOOLTIP"] = "当这个键覆盖时,其他被按下的按键将视为移动, 而不是指挥快捷键.\n按着这个键,通过WASD移动."
kTranslateMessage["COMBINDINGS_OVERHEAD_ZOOM_DECREASE"] = "降低指挥视角高度"
kTranslateMessage["COMBINDINGS_OVERHEAD_ZOOM_INCREASE"] = "增加指挥视角高度"
kTranslateMessage["COMBINDINGS_OVERHEAD_ZOOM_RESET"] = "重置指挥视角高度"


-- kTranslateMessage["COMBINDINGS_USE_MICROPHONE_LOCAL_"] = "开启区域(本地)麦克风"

---Advanced
kTranslateMessage["ADVANCED_CATEGORY_UI"] = "UI界面"
kTranslateMessage["ADVANCED_CATEGORY_HUD"] = "HUD抬头显示器"
kTranslateMessage["ADVANCED_CATEGORY_DAMAGE"] = "伤害"
kTranslateMessage["ADVANCED_CATEGORY_MAP"] = "地图"
kTranslateMessage["ADVANCED_CATEGORY_STATS"] = "状态"
kTranslateMessage["ADVANCED_CATEGORY_GRAPHICS"] = "画面"
kTranslateMessage["ADVANCED_CATEGORY_CROSSHAIR"] = "准星"
kTranslateMessage["ADVANCED_CATEGORY_MISC"] = "杂项"

---Graphics
kTranslateMessage["SHADOWS"]="阴影"
kTranslateMessage["BLOOM"]="全屏泛光"
kTranslateMessage["BLOOM_TOOLTIP"] = "亮的物体将产生泛光."
kTranslateMessage["AF"]="各向异性过滤"

kTranslateMessage["VSYNC"]="垂直同步"
kTranslateMessage["DOUBLE_BUFFERED"]="双重缓冲"
kTranslateMessage["TRIPLE_BUFFERED"]="三重缓冲"
kTranslateMessage["REFLECTIONS"]="反射"
kTranslateMessage["AMBIENT_OCCLUSION"]="环境光遮蔽"

kTranslateMessage["DISPLAY"]="显示设备"
kTranslateMessage["RESOLUTION"]="分辨率"
kTranslateMessage["WINDOW_MODE"]="窗口模式"
kTranslateMessage["WINDOW_MODE_WINDOWED"] = "窗口化"
kTranslateMessage["WINDOW_MODE_FULLSCREEN"] = "全屏"
kTranslateMessage["WINDOW_MODE_FULLSCREEN_WINDOWED"] = "全屏窗口化"
kTranslateMessage["MAX_FPS"]="最大帧率"
kTranslateMessage["MAXFPS_TOOLTIP"]="设置你的最大刷新率上限"
kTranslateMessage["GPU_MEMORY"]="GPU 显存"
kTranslateMessage["OPTION_TEXTURE_MANAGEMENT_TOOLTIP"] = "选择要占用的显存,优化纹理传输."
kTranslateMessage["PARTICLE_QUALITY"]="粒子质量"
kTranslateMessage["PTION_PARTICLE_QUALITY_TOOLTIP"] = "火焰与烟雾等的粒子效果质量."

kTranslateMessage["REFRACTION_QUALITY"]="折射质量"
kTranslateMessage["OPTION_REFRACTION_QUALITY_TOOLTIP"] = "折射效果质量.高级将采用更多采样带来更好的折射贴图"

kTranslateMessage["TEXTURE_QUALITY"]="贴图品质"
kTranslateMessage["OPTION_TEXTUREQUALITY"] = " 1GB-1.5GB显存推荐使用中等."
kTranslateMessage["ANTI_ALIASING"]="全屏抗锯齿"
kTranslateMessage["OPTION_ANTI_ALIASING"] = "减少场景的边缘锯齿.TAA (仅DirectX11) 质量最佳,性能较差.\nFXAA性能最好,但是质量较差,尤其针对细小的表面纹理."

kTranslateMessage["OPTION_TEXTUREQUALITY"] = " 1GB-1.5GB显存推荐使用中等."
kTranslateMessage["LIGHT_QUALITY"]="光源质量"
kTranslateMessage["OPTION_LIGHT_QUALITY "]= "关卡的光源质量,更多的光效果更好,也更卡."
kTranslateMessage["DECAL"] = "贴花时长"
kTranslateMessage["DECAL_LIFETIME_TOOLTIP"] = "决定多长时间后(分钟)贴花消失,越小性能越好."

kTranslateMessage["FOG"] = "雾效."
kTranslateMessage["OPTION_FOG_TOOLTIP"] = "雾效质量,调低后雾效会降低并带来更好的性能."

kTranslateMessage["COLORBLIND_MODE"] = "色盲模式"
kTranslateMessage["COLORBLIND_PROTANOPIA"] = "红色盲"
kTranslateMessage["COLORBLIND_DEUTERANOPIA"] = "绿色盲"
kTranslateMessage["COLORBLIND_TRITANOPIA"] = "蓝色盲"

kTranslateMessage["ATMOSPHERICS"]="大气雾效"
kTranslateMessage["ATMOSPHERICS_TOOLTIP"] = "光源(部分)将产生<上帝光>效果"
kTranslateMessage["ATMO_DENSITY"] = "大气密度"
kTranslateMessage["ATMO_DENSITY_TOOLTIP"] = "大气雾效的强度(仅在游戏内显示)."
kTranslateMessage["ATMO_QUALITY"] = "大气雾效质量"
kTranslateMessage["ATMO_QUALITY_TT"] = "大气雾效的渲染分辨率.越高效果越好.\n最高的效果将赢得D哥的心."

kTranslateMessage["MENU_INFESTATION"] = "菌毯效果"
kTranslateMessage["MENU_INFESTATION_TOOLTIP"] = "卡拉异形建筑邻近的菌毯质量"
kTranslateMessage["OPTION_GAMMA"] = "伽马矫正"
---Sound
kTranslateMessage["SOUND_MUTE_MINIZED"] = "最小化禁音"
kTranslateMessage["SOUND_MUTE_MINIZED_TTIP"] = "游戏最小化时将屏蔽所有音效"
kTranslateMessage["SOUND_VOLUME"] = "全局音量"
kTranslateMessage["OUTPUT_DEVICE"] = "输出设备"
kTranslateMessage["INPUT_DEVICE"] = "输入设备"
kTranslateMessage["AMBIENT_VOLUME"] = "环境音量"
kTranslateMessage["AMBIENT_VOLUME_TOOLTIP"] = "调整地图的环境音量,百分比乘于到原音量"
kTranslateMessage["MUSIC_VOLUME"] = "音乐音量"
kTranslateMessage["HIT_SOUND_VOLUME"]="命中提示音量"
kTranslateMessage["HIT_SOUND_PITCH"]="命中提示音调"
kTranslateMessage["HIT_SOUND_PITCH_TOOLTIP"]="调整命中提示的音调."
kTranslateMessage["VOICE_VOLUME"]="语音音量"
kTranslateMessage["VOICE_VOLUME_TOOLTIP"]="其他玩家语音的音量大小."
kTranslateMessage["MICROPHONE_RELEASE_DELAY"]="麦克风延迟."
kTranslateMessage["MICROPHONE_RELEASE_DELAY_TTIP"]="松开后继续监听麦克风的秒数."
kTranslateMessage["MICROPHONE_GAIN"]="麦克风输入."
kTranslateMessage["MICROPHONE_LEVEL"]="麦克风输入音量."


---MOD
kTranslateMessage["MENU_MANAGE_MODS"] = "管理插件"
kTranslateMessage["MENU_MODS_MANAGEMENT_DISABLED_TOOLTIP"] = "运行中无法进行插件管理"
kTranslateMessage["MENU_MANAGE_MODS"] = "正在运行的MOD:\n"
kTranslateMessage["MOD_STATUS_AVAILABLE"] = "100%"
kTranslateMessage["MOD_STATUS_DOWNLOADING"] = "下载中..."
kTranslateMessage["MOD_STATUS_GETTING_INFO"] = "获取信息..."
kTranslateMessage["MOD_STATUS_UNPACKING"] = "解压中..."
kTranslateMessage["MOD_STATUS_UNKNOWN"] = "未知"

kTranslateMessage["MODS_ACTIVE"] = "启用中"
kTranslateMessage["MODS_NAME"] = "名字"
kTranslateMessage["MODS_STATE"] = "状态"
kTranslateMessage["MODS_STATE_1"] = "获取信息"
kTranslateMessage["MODS_STATE_2"] = "加入下载队列"
kTranslateMessage["MODS_STATE_3"] = "下载中"
kTranslateMessage["MODS_STATE_4"] = "不可用"
kTranslateMessage["MODS_STATE_5"] = "可用"
kTranslateMessage["MODS_STATE_6"] = "解压"
kTranslateMessage["MODS_SUBSCRIBED"] = "已订阅"

---ThunderDome
kTranslateMessage["THUNDERDOME_REWARDS_PULLOUT_TITLE"] = "匹配模式奖励"
kTranslateMessage["CALLINGCARD_CUSTOMIZER_TOOLTIP"] = "自定义击杀卡"