kShineTranslations={}
kShineTranslations["Map Vote"]="换图投票"
kShineTranslations["MOTD"]="服务器信息"
kShineTranslations["Shuffle"]="洗牌分队"
kShineTranslations["Surrender"]="投降"
kShineTranslations["Unstuck"]="尝试脱困"
kShineTranslations["Switch Server"]="其他服务器"
kShineTranslations["Vote to Draw"]="投票平局"
kShineTranslations["CLIENT_CONFIG_MENU"]="Shine本地设置"
kShineTranslations["ADMIN_MENU"]="管理菜单"

kShineTranslations["SECOND"] = "{Value:Pluralise:秒|秒}"
kShineTranslations["MINUTE"] = "{Value:Pluralise:分钟|分钟}"
kShineTranslations["HOUR"] = "{Value:Pluralise:小时|小时}"
kShineTranslations["DAY"] = "{Value:Pluralise:天|days}"
kShineTranslations["WEEK"] ="{Value:Pluralise:星期|星期}"

kShineTranslations["ERROR_TAG"]="[错误]"
kShineTranslations["[Shuffle]"]="[洗牌]"
kShineTranslations["[Map Vote]"]="[换图]"
kShineTranslations["[AllTalk]"]="[全局语音]"
kShineTranslations["[Unstuck]"]="[脱困]"

kShineTranslations["SUCCESS"]="成功!"
kShineTranslations["ERROR_NOT_ALIVE"]="你无法在你死了的时候卡墙自救."
kShineTranslations["ERROR_WAIT"]= "必须等待{TimeLeft:Duration}后才能再次使用脱困"
kShineTranslations["ERROR_FAIL"]= "无法脱困,请于{TimeLeft:Duration}后再次尝试."

kShineTranslations["MARINE"]="边境拓荒者部队"
kShineTranslations["ALIEN"]="卡拉异型"
kShineTranslations["SAY_ALL"]="对所有人发言"
kShineTranslations["SAY_TEAM"]="对队伍内发言"
kShineTranslations["WAITING_FOR_BOTH"]="正在等待双方的指挥官"

kShineTranslations["TEAM_PREFERENCE_SET_MARINE"]="队伍偏好已设置为:陆战队"
kShineTranslations["TEAM_PREFERENCE_SET_ALIEN"]="队伍偏好已设置为:卡拉异形"
kShineTranslations["TEAM_PREFERENCE_SET_NONE"]="队伍偏已重置"

kShineTranslations["ERROR_WRONG_TEAM"]="无法在当前队伍发起投降."
kShineTranslations["ERROR_ROUND_TIME"]="现在太早无法发起投降."

kShineTranslations["ERROR_ROUND_NOT_STARTED"]="对局还未开始,无法发起平局."
kShineTranslations["ERROR_CANNOT_VOTE_ON_CURRENT_TEAM"]="无法在当前队伍发起平局."

kShineTranslations["ENABLE_ALLTALK"]="投票开启全局语音"
kShineTranslations["DISABLE_ALLTALK"]="投票关闭全局语音"
kShineTranslations["TEAM_PREFERENCE_HINT"]="队伍偏好"
kShineTranslations["ALLTALK_ENABLED"]="全局语音正处于开启状态"
kShineTranslations["ALLTALK_NOTIFY_ENABLED"]="全局语音已开启"
kShineTranslations["ALLTALK_NOTIFY_DISABLED"]="全局语音已关闭"

kShineTranslations["ACCEPT_FRIEND_GROUP_INVITE"]="接受组队"
kShineTranslations["DECLINE_FRIEND_GROUP_INVITE"]="拒绝组队"

kShineTranslations["ERROR_NOT_ENOUGH_PLAYERS"]="当前人数不足,无法洗牌分队."
-- Map Vote
kShineTranslations["VOTE"]="投票进行中"
kShineTranslations["RTV_STARTED"]="投票正在进行中!"
kShineTranslations["TOGGLE_MAP_OVERVIEW_TOOLTIP"]="显示地图总览"
kShineTranslations["SHOW_MOD_TOOLTIP"]="跳转到创意工坊"
kShineTranslations["VOTE_COUNTER"]= "{NumVotes} {NumVotes:Pluralise:vote|票}"
kShineTranslations["MAP_VOTE_MENU_SINGLE_CHOICE_DESCRIPTION"]="给你想玩的下一张地图投上一票"
kShineTranslations["NOT_ENOUGH_VOTES"]="投票数不足,换图投票失败."

kShineTranslations["NOMINATE_FAIL"]= "你不能提名当前地图."
kShineTranslations["NOMINATE_DENIED"]= "已达到了允许提名次数的上限."
kShineTranslations["ALREADY_NOMINATED"]= "{MapName}已经被提名了."
kShineTranslations["NOMINATIONS_FULL"]= "提名已满."
kShineTranslations["NOMINATED_MAP"]= "{TargetName}为换图投票提名了{MapName}."
kShineTranslations["PLAYER_VOTED"]= "{TargetName}{Revote:BoolToPhrase:又投给了|投给了}{MapName}. （目前有{Votes}{Votes:Pluralise:票|票},总共有{TotalVotes}人参与了投票）"
kShineTranslations["PLAYER_VOTED_PRIVATE"]= "你{Revote:BoolToPhrase:又投给了|投给了}{MapName}. （目前有{Votes}{Votes:Pluralise:票|票},总共有{TotalVotes}人参与了投票)"
kShineTranslations["WINNER_VOTES"]= "{MapName} 以 {Votes}/{TotalVotes} 张票数赢得了投票"
kShineTranslations["EXTENDING_TIME"]= "当前地图时间延长{Duration:Duration}"

kShineTranslations["TIME_LEFT"]= "此地图还剩下{Duration:Duration}"

kShineTranslations["MAP_EXTENDED_TIME"]= "地图被{Duration:Sign:缩短|延长}了{Duration:Abs::Duration}"
kShineTranslations["VOTES_TIED"]= "票数在{MapNames}之间持平."
kShineTranslations["CHOOSING_RANDOM_MAP"]= "正在随机选择地图,系统选择了：{MapName}."
kShineTranslations["MAP_CHANGING"]= "服务器将在{Duration:Duration}后更换地图."

kShineTranslations["FORCED_VOTE"]= "强制开始了换图投票"
kShineTranslations["CANT_FORCE"]= "无法发起新的投票，当前已经有一项投票正在进行中"

kShineTranslations["VOTE_FAIL_MAP_CHANGE"]= "正在换图,无法发起投票."
kShineTranslations["VOTE_FAIL_INSUFFICIENT_PLAYERS"]= "所需玩家人数不足,无法发起投票."
kShineTranslations["VOTE_FAIL_TIME"]= "眼下你无法发起换图投票."
kShineTranslations["VOTE_FAIL_IN_PROGRESS"]= "一项投票已经正在进行中了."
kShineTranslations["VOTE_FAIL_ALREADY_VOTED"]= "你已经投过发起换图投票了."
kShineTranslations["VOTE_FAIL_INVALID_MAP"]= "{MapName}并不是一个有效的地图名."
kShineTranslations["VOTE_FAIL_VOTED_MAP"]= "你已经投过{MapName}的票了."