--Common
kShineTranslations={}
kShineTranslations["TIME_VALUE"]= "{Value} {TimeUnit}"
kShineTranslations["TIME_SENTENCE"]= "{Before}{After}"
kShineTranslations["TIME_SEPARATOR"]= ","

kShineTranslations["SECOND"] = "{Value:Pluralise:秒|秒}"
kShineTranslations["MINUTE"] = "{Value:Pluralise:分钟|分钟}"
kShineTranslations["HOUR"] = "{Value:Pluralise:小时|小时}"
kShineTranslations["DAY"] = "{Value:Pluralise:天|天}"
kShineTranslations["WEEK"] ="{Value:Pluralise:星期|星期}"


kShineTranslations["MARINE"]="边境拓荒者部队"
kShineTranslations["ALIEN"]="卡拉异型"
kShineTranslations["ERROR_TAG"]="[错误]"
kShineTranslations["BACK"]="上一级"

--Plugins
kShinePluginsTranslations={}
kShinePluginsTranslations["Core"]={}
kShinePluginsTranslations["Core"]["Map Vote"]="换图投票"
kShinePluginsTranslations["Core"]["Shuffle"]="洗牌分队"

kShinePluginsTranslations["Core"]["Surrender"]="投降"
kShinePluginsTranslations["Core"]["Unstuck"]="尝试脱困"
kShinePluginsTranslations["Core"]["MOTD"]="日常信息"
kShinePluginsTranslations["Core"]["CLIENT_CONFIG_MENU"]="Shine本地设置"
kShinePluginsTranslations["Core"]["ADMIN_MENU"]="管理菜单"

kShinePluginsTranslations["Core"]["NAME"]="名字"
kShinePluginsTranslations["Core"]["TEAM"]="队伍"
kShinePluginsTranslations["Core"]["ADMIN_MENU_COMMANDS_TAB"]="玩家指令"
kShinePluginsTranslations["Core"]["ADMIN_MENU_PLAYERS_HELP"]="请选择一位或多位玩家."
kShinePluginsTranslations["Core"]["ADMIN_MENU_STATUS_TAB"]="服务器状态"
kShinePluginsTranslations["Core"]["ADMIN_MENU_ABOUT_TAB"]="关于"
kShinePluginsTranslations["Core"]["ADMIN_MENU_OPEN_WIKI"]="WIKI页面"
kShinePluginsTranslations["Core"]["SYSTEM_NOTIFICATIONS_LOADING"]="加载中.."
kShinePluginsTranslations["Core"]["SYSTEM_NOTIFICATIONS_OK"]="良好"
kShinePluginsTranslations["Core"]["SYSTEM_NOTIFICATIONS_NOTIFICATION_LEVEL_DESCRIPTION"]="在此刻通知:"
kShinePluginsTranslations["Core"]["SYSTEM_NOTIFICATIONS_LEVEL_WARNING"]= "启动时出现警告与错误"
kShinePluginsTranslations["Core"]["SYSTEM_NOTIFICATIONS_LEVEL_ERROR"]= "启动时出现报错"

kShinePluginsTranslations["chatbox"]={}
kShinePluginsTranslations["chatbox"]["SAY_ALL"]="对所有人发言"
kShinePluginsTranslations["chatbox"]["SAY_TEAM"]="对队伍内发言"

kShinePluginsTranslations["motd"]={}
kShinePluginsTranslations["motd"]["MESSAGE_OF_THE_DAY"]= "本服文档"
kShinePluginsTranslations["motd"]["OPEN_IN_STEAM"]= "在Steam中打开"
kShinePluginsTranslations["motd"]["LOADING"]= "加载文档中..."

kShinePluginsTranslations["unstuck"]={}
kShinePluginsTranslations["unstuck"]["NOTIFY_PREFIX"]="[卡墙自救]"
kShinePluginsTranslations["unstuck"]["SUCCESS"]="成功!"
kShinePluginsTranslations["unstuck"]["ERROR_NOT_ALIVE"]="你无法在你死了的时候卡墙自救."
kShinePluginsTranslations["unstuck"]["ERROR_WAIT"]= "必须等待{TimeLeft:Duration}后才能再次使用脱困"
kShinePluginsTranslations["unstuck"]["ERROR_FAIL"]= "脱困失败,请于{TimeLeft:Duration}后再次尝试."

kShinePluginsTranslations["votedraw"]={}
kShinePluginsTranslations["votedraw"]["NOTIFY_PREFIX"]="[平局]"
kShinePluginsTranslations["votedraw"]["VOTEMENU_BUTTON"]="投票平局"
kShinePluginsTranslations["votedraw"]["PLAYER_VOTED"]= "{PlayerName} 已经经受不住折磨想要平局了 (还需 {VotesNeeded} 票)"
kShinePluginsTranslations["votedraw"]["PLAYER_VOTED_PRIVATE"]= "你选择投票平局 (还需 {VotesNeeded:Pluralise: 票| 票})"
kShinePluginsTranslations["votedraw"]["ERROR_ALREADY_VOTED"]= "你已经投过平局票."
kShinePluginsTranslations["votedraw"]["ERROR_MUST_WAIT"]= "必须等待 {SecondsToWait:Duration} 才能开始投票平局."
kShinePluginsTranslations["votedraw"]["ERROR_CANNOT_VOTE_ON_CURRENT_TEAM"]= "你无法在当前队伍发起平局投票."
kShinePluginsTranslations["votedraw"]["ERROR_ROUND_NOT_STARTED"]= "必须开局才能开始投票平局."

kShinePluginsTranslations["ban"]={}
kShinePluginsTranslations["ban"]["CATEGORY"]="封禁目录"
kShinePluginsTranslations["ban"]["BAN"]="封禁"
kShinePluginsTranslations["ban"]["BAN_TIP"]="封禁这名玩家,踢出且时限内无法加入服务器"
kShinePluginsTranslations["ban"]["Bans"]="封禁名单"
kShinePluginsTranslations["ban"]["NAME"]="名字"
kShinePluginsTranslations["ban"]["BANNED_BY"]="执行人"
kShinePluginsTranslations["ban"]["EXPIRY"]="期限"
kShinePluginsTranslations["ban"]["ADD_BAN"]="新增封禁"
kShinePluginsTranslations["ban"]["UNBAN"]="解除封禁"
kShinePluginsTranslations["ban"]["ADD_BAN_TITLE"]="封禁玩家"
kShinePluginsTranslations["ban"]["SEARCH_HINT"]="查找指定ID"
kShinePluginsTranslations["ban"]["TOTAL_RESULTS_TIP"]= "共有 {TotalResults} 封禁"
kShinePluginsTranslations["ban"]["SELECT_PLAYER"]= "选择玩家"
kShinePluginsTranslations["ban"]["DURATION_LABEL"]= "封禁时间 (单位为分钟,0代表永久)"
kShinePluginsTranslations["ban"]["DURATION_HINT"]= "输入封禁时间"
kShinePluginsTranslations["ban"]["REASON"]= "理由"

kShinePluginsTranslations["basecommands"]={}
kShinePluginsTranslations["basecommands"]["ALL_TALK_TAG"]="[全局语音]"
kShinePluginsTranslations["basecommands"]["CATEGORY"]="玩家操作目录"
kShinePluginsTranslations["basecommands"]["EJECT"]="罢免指挥"
kShinePluginsTranslations["basecommands"]["EJECT_TIP"]="只对指挥站里的玩家有效"
kShinePluginsTranslations["basecommands"]["KICK"]="踢出"
kShinePluginsTranslations["basecommands"]["KICK_TIP"]="将玩家踢出服务器"
kShinePluginsTranslations["basecommands"]["KICK_NO_REASON"]="无理由"
kShinePluginsTranslations["basecommands"]["KICK_TROLLING"]="折磨队友"
kShinePluginsTranslations["basecommands"]["KICK_LANGUAGE"]="不当言论"
kShinePluginsTranslations["basecommands"]["KICK_MIC_SPAM"]="炸麦"
kShinePluginsTranslations["basecommands"]["KICK_AFK"]="挂机"
kShinePluginsTranslations["basecommands"]["KICK_CUSTOM"]="填写理由"
kShinePluginsTranslations["basecommands"]["RESET_GAME"]="重置了对局."
kShinePluginsTranslations["basecommands"]["GAG"]="禁言与禁麦"
kShinePluginsTranslations["basecommands"]["GAG_TIP"]="无法打字与开麦交流,且叫不了血包"
kShinePluginsTranslations["basecommands"]["UNGAG"]="解除禁言与禁麦"
kShinePluginsTranslations["basecommands"]["UNGAG_TIP"]="解禁了"
kShinePluginsTranslations["basecommands"]["GAG_UNTIL_MAP_CHANGE"]="到换图之前"
kShinePluginsTranslations["basecommands"]["PERMANENTLY"]="永久"
kShinePluginsTranslations["basecommands"]["FORCE_RANDOM"]="随机分队"
kShinePluginsTranslations["basecommands"]["FORCE_RANDOM_TIP"]="使他们随机加入对局"
kShinePluginsTranslations["basecommands"]["READY_ROOM"]="回到预备室"
kShinePluginsTranslations["basecommands"]["READY_ROOM_TIP"]="使其回到预备室"
kShinePluginsTranslations["basecommands"]["SET_TEAM"]="设置队伍"
kShinePluginsTranslations["basecommands"]["FORCE_SET_TEAM"]="{TeamName} (强制)"
kShinePluginsTranslations["basecommands"]["SET_TEAM_TIP"]="将玩家指定到特定队伍"
kShinePluginsTranslations["basecommands"]["READY_ROOM"]= "预备室"
kShinePluginsTranslations["basecommands"]["CHANGE_TEAM_ALIEN"]= "将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到卡拉异形."
kShinePluginsTranslations["basecommands"]["CHANGE_TEAM_READY_ROOM"]= "将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到预备室."
kShinePluginsTranslations["basecommands"]["CHANGE_TEAM_SPECTATOR"]= "将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到到观战."
kShinePluginsTranslations["basecommands"]["CHANGE_TEAM_MARINE"]="将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到边境拓荒者部队."
kShinePluginsTranslations["basecommands"]["MAPS"]="地图列表"
kShinePluginsTranslations["basecommands"]["MAP"]="地图名"
kShinePluginsTranslations["basecommands"]["CHANGE_MAP"]="强制地图"
kShinePluginsTranslations["basecommands"]["CHANGE_MAP_TIP"]="强制切换到这张地图"
kShinePluginsTranslations["basecommands"]["CALL_VOTE"]="换图投票"
kShinePluginsTranslations["basecommands"]["CALL_VOTE_TIP"]="强制发起换图投票"
kShinePluginsTranslations["basecommands"]["PLUGINS"]="插件目录"
kShinePluginsTranslations["basecommands"]["PLUGIN"]="插件名"
kShinePluginsTranslations["basecommands"]["STATE"]="状态"
kShinePluginsTranslations["basecommands"]["UNLOAD_PLUGIN"]="卸载"
kShinePluginsTranslations["basecommands"]["LOAD_PLUGIN"]="安装"

-- Fun commands
kShinePluginsTranslations["funcommands"]={}
kShinePluginsTranslations["funcommands"]["CATEGORY"]="怪指令目录"
kShinePluginsTranslations["funcommands"]["GOTO"]="传送"
kShinePluginsTranslations["funcommands"]["GOTO_TIP"]="传送至玩家身边"
kShinePluginsTranslations["funcommands"]["BRING"]="呼来"
kShinePluginsTranslations["funcommands"]["BRING_TIP"]="将玩家传送到你身边"
kShinePluginsTranslations["funcommands"]["SLAY"]="击杀"
kShinePluginsTranslations["funcommands"]["SLAY_TIP"]="强制击杀这命玩家"
kShinePluginsTranslations["funcommands"]["DARWIN_MODE"]="上帝模式"
kShinePluginsTranslations["funcommands"]["DARWIN_MODE_TIP"]="锁血锁弹药"
kShinePluginsTranslations["funcommands"]["ENABLE"]="开启"
kShinePluginsTranslations["funcommands"]["DISABLE"]="关闭"

kShineTranslations["ENABLE_ALLTALK"]="投票开启全局语音"
kShineTranslations["DISABLE_ALLTALK"]="投票关闭全局语音"
kShineTranslations["TEAM_PREFERENCE_HINT"]="队伍偏好"
kShineTranslations["ALLTALK_ENABLED"]="全局语音正处于开启状态"
kShineTranslations["ALLTALK_DISABLED"]="全局语音已关闭"
kShineTranslations["ALLTALK_NOTIFY_ENABLED"]="已开启."
kShineTranslations["ALLTALK_NOTIFY_DISABLED"]="已关闭."
kShineTranslations["PLAYER_VOTED_ENABLE"] = "{PlayerName} 投票开启全局语音 (还需  {VotesNeeded} {VotesNeeded:Pluralise: 票| 票})"
kShineTranslations["PLAYER_VOTED_DISABLE"] = "{PlayerName} 投票关闭全局语音 (还需  {VotesNeeded} {VotesNeeded:Pluralise: 票| 票})"
kShineTranslations["ERROR_ALREADY_VOTED_DISABLE"] = "{PlayerName} 投票关闭全局语音 (还需  {VotesNeeded} {VotesNeeded:Pluralise: 票| 票})"	
kShineTranslations["ERROR_ALREADY_VOTED_ENABLE"]= "已参与过开启全局语音投票."
kShineTranslations["ERROR_ALREADY_VOTED_DISABLE"]= "已参与过关闭全局语音投票."
kShineTranslations["ERROR_CANNOT_VOTE_IN_SPECTATE"]= "观察者不允许参与全局语音投票."

kShinePluginsTranslations["serverswitch"]={}
kShinePluginsTranslations["serverswitch"]["VOTEMENU_BUTTON"]="服务器列表"

kShinePluginsTranslations["workshopupdater"]={}
kShinePluginsTranslations["workshopupdater"]["NOTIFY_PREFIX"]= "[创意工坊]"
kShinePluginsTranslations["workshopupdater"]["MOD_CHANGED"]= "插件 <{ModName}> 已经更新了."
kShinePluginsTranslations["workshopupdater"]["MAY_BE_UNABLE_TO_CONNECT"]= "在换图之前,部分玩家将无法连接进入服务器."
kShinePluginsTranslations["workshopupdater"]["MAP_CYCLE"]= "地图将 {TimeLeft:NonZero:于} {TimeLeft:Duration:现在} 后强制更换."

kShinePluginsTranslations["votesurrender"]={}
kShinePluginsTranslations["votesurrender"]["ERROR_WRONG_TEAM"]="无法在当前队伍发起投降."
kShinePluginsTranslations["votesurrender"]["ERROR_ROUND_TIME"]="现在太早无法发起投降."
kShinePluginsTranslations["votesurrender"]["ERROR_ROUND_NOT_STARTED"]="对局还未开始,无法发起投票."
kShinePluginsTranslations["votesurrender"]["ERROR_CANNOT_VOTE_ON_CURRENT_TEAM"]="无法在当前队伍发起投票."

kShinePluginsTranslations["votealltalk"]={}
kShinePluginsTranslations["votealltalk"]["NOTIFY_PREFIX"]="[全局语音投票]"

kShinePluginsTranslations["voterandom"]={}
kShinePluginsTranslations["voterandom"]["NOTIFY_PREFIX"]="[洗牌分队]"
kShinePluginsTranslations["voterandom"]["TEAM_PREFERENCE_SET_MARINE"]="队伍偏好已设置为:陆战队"
kShinePluginsTranslations["voterandom"]["TEAM_PREFERENCE_SET_ALIEN"]="队伍偏好已设置为:卡拉异形"
kShinePluginsTranslations["voterandom"]["TEAM_PREFERENCE_SET_NONE"]="队伍偏好已重置"
kShinePluginsTranslations["voterandom"]["ACCEPT_FRIEND_GROUP_INVITE"]="接受组队"
kShinePluginsTranslations["voterandom"]["DECLINE_FRIEND_GROUP_INVITE"]="拒绝组队"
kShinePluginsTranslations["voterandom"]["TEAMS_SHUFFLED_FOR_DURATION_HIVE_BASED"]= "强制洗牌分队将持续 {Duration:Duration}."
kShinePluginsTranslations["voterandom"]["TEAM_ENFORCING_TIMELIMIT_HIVE_BASED"]= "强制洗牌分队时限已到."
kShinePluginsTranslations["voterandom"]["ERROR_NOT_ENOUGH_PLAYERS"] ="当前人数不足,无法洗牌分队."
kShinePluginsTranslations["voterandom"]["PLAYER_VOTED_HIVE_BASED"] = "{PlayerName} 投票洗牌分队 (还需  {VotesNeeded} {VotesNeeded:Pluralise: 票| 票})"
kShinePluginsTranslations["voterandom"]["SHUFFLING_TEAMS_SHUFFLE_HIVE"] = "基于玩家的战力洗牌."
kShinePluginsTranslations["voterandom"]["SHUFFLE_AND_RESTART_SHUFFLE_HIVE"] = "基于玩家的战力洗牌,对局已重启."
kShinePluginsTranslations["voterandom"]["ERROR_ALREADY_VOTED_HIVE_BASED"] = "你已经投过洗牌分队了."
kShinePluginsTranslations["voterandom"]["ERROR_CONSTRAINTS"]="当前分数已平衡."

-- PreGame
kShinePluginsTranslations["pregame"]={}
kShinePluginsTranslations["pregame"]["NOTIFY_PREFIX"]= "[游戏开局]"
kShinePluginsTranslations["pregame"]["GAME_START"]= "战局即将开始...%s"
kShinePluginsTranslations["pregame"]["GAME_START_SOON"]= "对局即将于{Duration:Duration}后开始"
kShinePluginsTranslations["pregame"]["ABORT_COMMANDER_DROP"] = "开局终止,有一方的指挥登出指挥站."
kShinePluginsTranslations["pregame"]["ALIENS_HAVE_COMMANDER"]= "卡拉异形已有指挥,边境拓荒者部队还剩 {TimeLeft:Duration} 去选择他们的指挥员."
kShinePluginsTranslations["pregame"]["MARINES_HAVE_COMMANDER"]= "边境拓荒者部队已有指挥,卡拉异形还剩 {TimeLeft:Duration} 去选择他们的指挥员."
kShinePluginsTranslations["pregame"]["WAITING_FOR_BOTH"]="正在等待双方的指挥官."
kShinePluginsTranslations["pregame"]["WAITING_FOR_ALIENS"]= "等待卡拉异形选择他们的指挥员."
kShinePluginsTranslations["pregame"]["WAITING_FOR_MARINES"]= "等待边境拓荒者部队选择他们的指挥员."

-- Map Vote
kShinePluginsTranslations["mapvote"]={}
kShinePluginsTranslations["mapvote"]["NOTIFY_PREFIX"]="[换图]"
kShinePluginsTranslations["mapvote"]["TIME_LEFT_NOTIFY"]="{Duration:Duration} 后将会切换到下一张地图."
kShinePluginsTranslations["mapvote"]["VOTE"]="投票进行中"
kShinePluginsTranslations["mapvote"]["MAP_VOTE_MENU_TITLE"]="正在进行换图投票"
kShinePluginsTranslations["mapvote"]["RTV_STARTED"]="投票正在进行中!"
kShinePluginsTranslations["mapvote"]["RTV_VOTED"] = "{TargetName} 想要发起换图投票 (还需{VotesNeeded}票才能通过)"
kShinePluginsTranslations["mapvote"]["TOGGLE_MAP_OVERVIEW_TOOLTIP"]="显示地图总览"
kShinePluginsTranslations["mapvote"]["SHOW_MOD_TOOLTIP"]="跳转到创意工坊"
kShinePluginsTranslations["mapvote"]["VOTE_COUNTER"]= "{NumVotes} {NumVotes:Pluralise: 票| 票}"
kShinePluginsTranslations["mapvote"]["MAP_VOTE_MENU_SINGLE_CHOICE_DESCRIPTION"]="给你想玩的下一张地图投上一票"
kShinePluginsTranslations["mapvote"]["NOT_ENOUGH_VOTES"]="投票数不足,换图投票失败."
kShinePluginsTranslations["mapvote"]["MAP_VOTE_MENU_CURRENT_MAP"]= "当前地图: {MapName}"
kShinePluginsTranslations["mapvote"]["MAP_VOTE_MENU_EXTEND_MAP"]= "延续 - {MapName}"
kShinePluginsTranslations["mapvote"]["NEXT_MAP_STARTED"]= "换图投票开始了."
kShinePluginsTranslations["mapvote"]["WINNER_CYCLING"]= "{MapName}赢得了投票,开始换图."

kShinePluginsTranslations["mapvote"]["NOMINATE_FAIL"]= "你不能提名当前地图."
kShinePluginsTranslations["mapvote"]["NOMINATE_DENIED"]= "已达到了允许提名次数的上限."
kShinePluginsTranslations["mapvote"]["ALREADY_NOMINATED"]= "{MapName}已经被提名了."
kShinePluginsTranslations["mapvote"]["NOMINATIONS_FULL"]= "提名已满."
kShinePluginsTranslations["mapvote"]["NOMINATED_MAP"]= "{TargetName}为换图投票提名了{MapName}."
kShinePluginsTranslations["mapvote"]["PLAYER_VOTED"]= "{TargetName}{Revote:BoolToPhrase:又投给了|投给了}{MapName}. （目前有{Votes}{Votes:Pluralise: 票| 票},总共有{TotalVotes}人参与了投票）"
kShinePluginsTranslations["mapvote"]["PLAYER_VOTED_PRIVATE"]= "你{Revote:BoolToPhrase:又投给了|投给了}{MapName}. （目前有{Votes}{Votes:Pluralise: 票| 票},总共有{TotalVotes}人参与了投票)"
kShinePluginsTranslations["mapvote"]["WINNER_VOTES"]= "{MapName} 以 {Votes}/{TotalVotes} 的比例赢得了投票."
kShinePluginsTranslations["mapvote"]["EXTENDING_TIME"]= "当前地图时间延长{Duration:Duration}"

kShinePluginsTranslations["mapvote"]["TIME_LEFT"]= "此地图还剩下{Duration:Duration}"

kShinePluginsTranslations["mapvote"]["MAP_EXTENDED_TIME"]= "地图被{Duration:Sign:缩短|延长}了{Duration:Abs::Duration}"
kShinePluginsTranslations["mapvote"]["VOTES_TIED"]= "票数在{MapNames}之间持平."
kShinePluginsTranslations["mapvote"]["CHOOSING_RANDOM_MAP"]= "正在随机选择地图,系统选择了：{MapName}."
kShinePluginsTranslations["mapvote"]["MAP_CHANGING"]= "服务器将在 {Duration:Duration} 后更换地图."

kShinePluginsTranslations["mapvote"]["FORCED_VOTE"]= "强制开始了换图投票"
kShinePluginsTranslations["mapvote"]["CANT_FORCE"]= "无法发起新的投票，当前已经有一项投票正在进行中"

kShinePluginsTranslations["mapvote"]["VOTE_FAIL_MAP_CHANGE"]= "正在换图,无法发起投票."
kShinePluginsTranslations["mapvote"]["VOTE_FAIL_INSUFFICIENT_PLAYERS"]= "所需玩家人数不足,无法发起投票."
kShinePluginsTranslations["mapvote"]["VOTE_FAIL_TIME"]= "眼下你无法发起换图投票."
kShinePluginsTranslations["mapvote"]["VOTE_FAIL_IN_PROGRESS"]= "一项投票已经正在进行中了."
kShinePluginsTranslations["mapvote"]["VOTE_FAIL_ALREADY_VOTED"]= "你已经投过发起换图投票了."
kShinePluginsTranslations["mapvote"]["VOTE_FAIL_INVALID_MAP"]= "{MapName}并不是一个有效的地图名."
kShinePluginsTranslations["mapvote"]["VOTE_FAIL_VOTED_MAP"]= "你已经投过{MapName}的票了."

--Readyroom Queue
kShinePluginsTranslations["readyroomqueue"]={}
kShinePluginsTranslations["readyroomqueue"]["NOTIFY_PREFIX"]="[入场队列]"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_CHANGED"]= "在你前面的玩家离开了队列. 目前的排队序号为 {Position}."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_CHANGED_VIP"]= "一个特权玩家插队了. 目前的排队序号为 {Position}."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_CHANGED"]= "A player in front of you left the reservered slot queue. You are the {Position} spectator in the reserved slot queue."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_CHANGED_VIP"]= "A VIP player joined the reservered slot queue in front of you. You are the {Position} spectator in the reserved slot queue."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_ADDED"]=  "开始排队! 当前的排队序号为 {Position}. 聊天框输入 !rr_dequeue 离开队列."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_ADDED"]= "You joined the reserved slot queue! Your current position is {Position}. To leave the queue enter !rr_dequeue into the chat."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_POSITION"]=  "当前的排队序号为 {Position}."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_POSITION"]= "Your current position in the reserved slot queue is {Position}."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_POSITION_UNKNOWN"]= "还未开始排队!"
kShinePluginsTranslations["readyroomqueue"]["DEQUEUE_SUCCESS"]= "停止了排队!"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_LEAVE"]= "排队成功. 已被挪到预备室!  感谢你的耐心等待,请尽快加入游戏."
kShinePluginsTranslations["readyroomqueue"]["ENQUEUE_ERROR_PLAYER"]= "只有观战可以进入排队!"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_INFORM"]= "如果你想进场游戏请按下 |F4建| 或者再聊天框输入 !rr_enqueue. 目前有 {Position} 个玩家正在排队!"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_WELCOME_BACK"]= "欢迎回来! 你的排队序号已被复原 ({Position}). 聊天框输入 !rr_dequeue 离开队列."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_WAITTIME"]= "当前服务器的平均排队时间为 %s. 可以考虑暖暖别的服务器."

kShinePluginsTranslations["readyroomqueue"]["QUEUE_CHANGED"]= "在你前面的玩家离开了队列. 目前的排队序号为 {Position}."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_CHANGED_VIP"]= "一个特权玩家插队了. 目前的排队序号为 {Position}."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_CHANGED"]= "A player in front of you left the reservered slot queue. You are the {Position} spectator in the reserved slot queue."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_CHANGED_VIP"]= "A VIP player joined the reservered slot queue in front of you. You are the {Position} spectator in the reserved slot queue."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_ADDED"]=  "开始排队! 当前的排队序号为 {Position}. 聊天框输入 !rr_dequeue 离开队列."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_ADDED"]= "You joined the reserved slot queue! Your current position is {Position}. To leave the queue enter !rr_dequeue into the chat."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_POSITION"]=  "当前的排队序号为 {Position}."
kShinePluginsTranslations["readyroomqueue"]["PIORITY_QUEUE_POSITION"]= "Your current position in the reserved slot queue is {Position}."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_POSITION_UNKNOWN"]= "还未开始排队!"
kShinePluginsTranslations["readyroomqueue"]["DEQUEUE_SUCCESS"]= "停止了排队!"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_LEAVE"]= "排队成功. 已被挪到预备室!  感谢你的耐心等待,请尽快加入游戏."
kShinePluginsTranslations["readyroomqueue"]["ENQUEUE_ERROR_PLAYER"]= "只有观战可以进入排队!"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_INFORM"]= "如果你想进场游戏请按下 |F4建| 或者再聊天框输入 !rr_enqueue. 目前有 {Position} 个玩家正在排队!"
kShinePluginsTranslations["readyroomqueue"]["QUEUE_WELCOME_BACK"]= "欢迎回来! 你的排队序号已被复原 ({Position}). 聊天框输入 !rr_dequeue 离开队列."
kShinePluginsTranslations["readyroomqueue"]["QUEUE_WAITTIME"]= "当前服务器的平均排队时间为 %s. 可以考虑暖暖别的服务器."