kShineTranslations={}
kShineTranslations["Map Vote"]="换图投票"
kShineTranslations["MOTD"]="服务器信息"
kShineTranslations["Shuffle"]="洗牌分队"
kShineTranslations["Surrender"]="投降"
kShineTranslations["Unstuck"]="尝试脱困"
kShineTranslations["Switch Server"]="其他服务器"
kShineTranslations["Vote to Draw"]="投票平局"
kShineTranslations["CLIENT_CONFIG_MENU"]="Shine本地设置"
kShineTranslations["ADMIN_MENU"]="管理菜单"

kShineTranslations["SECOND"] = "{Value:Pluralise:秒|秒}"
kShineTranslations["MINUTE"] = "{Value:Pluralise:分钟|分钟}"
kShineTranslations["HOUR"] = "{Value:Pluralise:小时|小时}"
kShineTranslations["DAY"] = "{Value:Pluralise:天|days}"
kShineTranslations["WEEK"] ="{Value:Pluralise:星期|星期}"

kShineTranslations["MARINE"]="边境拓荒者部队"
kShineTranslations["ALIEN"]="卡拉异型"
kShineTranslations["SAY_ALL"]="对所有人发言"
kShineTranslations["SAY_TEAM"]="对队伍内发言"

kShineTranslations["ERROR_TAG"]="[错误]"
--Unstuck
kShineTranslations["[Unstuck]"]="[脱困]"
kShineTranslations["SUCCESS"]="成功!"
kShineTranslations["ERROR_NOT_ALIVE"]="你无法在你死了的时候卡墙自救."
kShineTranslations["ERROR_WAIT"]= "必须等待{TimeLeft:Duration}后才能再次使用脱困"
kShineTranslations["ERROR_FAIL"]= "脱困失败,请于{TimeLeft:Duration}后再次尝试."


kShineTranslations["TEAM_PREFERENCE_SET_MARINE"]="队伍偏好已设置为:陆战队"
kShineTranslations["TEAM_PREFERENCE_SET_ALIEN"]="队伍偏好已设置为:卡拉异形"
kShineTranslations["TEAM_PREFERENCE_SET_NONE"]="队伍偏好已重置"

kShineTranslations["ERROR_WRONG_TEAM"]="无法在当前队伍发起投降."
kShineTranslations["ERROR_ROUND_TIME"]="现在太早无法发起投降."

kShineTranslations["ERROR_ROUND_NOT_STARTED"]="对局还未开始,无法发起平局."
kShineTranslations["ERROR_CANNOT_VOTE_ON_CURRENT_TEAM"]="无法在当前队伍发起平局."
-- Alltalk
kShineTranslations["[AllTalk]"]="[全局语音]"
kShineTranslations["ENABLE_ALLTALK"]="投票开启全局语音"
kShineTranslations["DISABLE_ALLTALK"]="投票关闭全局语音"
kShineTranslations["TEAM_PREFERENCE_HINT"]="队伍偏好"
kShineTranslations["ALLTALK_ENABLED"]="全局语音正处于开启状态"
kShineTranslations["ALLTALK_DISABLED"]="全局语音已关闭"
kShineTranslations["ALLTALK_NOTIFY_ENABLED"]="全局语音已开启"
kShineTranslations["ALLTALK_NOTIFY_DISABLED"]="全局语音已关闭"
kShineTranslations["PLAYER_VOTED_ENABLE"] = "{PlayerName} 投票开启全局语音 (还需  {VotesNeeded} {VotesNeeded:Pluralise:vote| 票})"
kShineTranslations["PLAYER_VOTED_DISABLE"] = "{PlayerName} 投票关闭全局语音 (还需  {VotesNeeded} {VotesNeeded:Pluralise:vote| 票})"
kShineTranslations["ERROR_ALREADY_VOTED_DISABLE"] = "{PlayerName} 投票关闭全局语音 (还需  {VotesNeeded} {VotesNeeded:Pluralise:vote| 票})"	
kShineTranslations["ERROR_ALREADY_VOTED_ENABLE"]= "已参与过开启全局语音投票."
kShineTranslations["ERROR_ALREADY_VOTED_DISABLE"]= "已参与过关闭全局语音投票."
kShineTranslations["ERROR_CANNOT_VOTE_IN_SPECTATE"]= "观察者不允许参与全局语音投票."
--MOD
kShineTranslations["[Workshop]"]= "[创意工坊]"
kShineTranslations["MOD_CHANGED"]= "MOD |{ModName}| 已经更新了."
kShineTranslations["MAY_BE_UNABLE_TO_CONNECT"]= "在换图之前,其他玩家们将无法连接进入服务器."
kShineTranslations["MAP_CYCLE"]= "地图将 {TimeLeft:NonZero:于} {TimeLeft:Duration:现在} 后强制更换."

-- Shuffle 
kShineTranslations["[Shuffle]"]="[洗牌]"
kShineTranslations["ACCEPT_FRIEND_GROUP_INVITE"]="接受组队"
kShineTranslations["DECLINE_FRIEND_GROUP_INVITE"]="拒绝组队"

kShineTranslations["TEAMS_SHUFFLED_FOR_DURATION_HIVE_BASED"]= "强制洗牌分队将持续 {Duration:Duration}."
kShineTranslations["TEAM_ENFORCING_TIMELIMIT_HIVE_BASED"]= "强制洗牌分队时限已到."
kShineTranslations["ERROR_NOT_ENOUGH_PLAYERS"] ="当前人数不足,无法洗牌分队."
kShineTranslations["PLAYER_VOTED_HIVE_BASED"] = "{PlayerName} 投票洗牌分队 (还需  {VotesNeeded} {VotesNeeded:Pluralise:vote| 票})"

kShineTranslations["SHUFFLING_TEAMS_SHUFFLE_HIVE"] = "基于玩家的战力洗牌."

kShineTranslations["CHANGE_TEAM_ALIEN"]= "将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到卡拉异形."
kShineTranslations["CHANGE_TEAM_READY_ROOM"]= "将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到预备室."
kShineTranslations["CHANGE_TEAM_SPECTATOR"]= "将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到到观战."
kShineTranslations["CHANGE_TEAM_MARINE"]="将 {TargetCount} {TargetCount:Pluralise:玩家|玩家} 分配到边境拓荒者部队."
-- PreGame
kShineTranslations["[Pre Game]"]= "[游戏开局]"
kShineTranslations["GAME_START"]= "战局即将开始...%s"
kShineTranslations["GAME_START_SOON"]= "对局即将于{Duration:Duration}后开始"
kShineTranslations["ABORT_COMMANDER_DROP"] = "开局终止,有一方的指挥登出指挥站."
kShineTranslations["ALIENS_HAVE_COMMANDER"]= "卡拉异形已有指挥,边境拓荒者部队还剩 {TimeLeft:Duration} 去选择他们的指挥员."
kShineTranslations["MARINES_HAVE_COMMANDER"]= "边境拓荒者部队已有指挥,卡拉异形还剩 {TimeLeft:Duration} 去选择他们的指挥员."
kShineTranslations["WAITING_FOR_BOTH"]="正在等待双方的指挥官."
kShineTranslations["WAITING_FOR_ALIENS"]= "等待卡拉异形选择他们的指挥员."
kShineTranslations["WAITING_FOR_MARINES"]= "等待边境拓荒者部队选择他们的指挥员."

-- Map Vote
kShineTranslations["[Map Vote]"]="[换图]"
kShineTranslations["VOTE"]="投票进行中"
kShineTranslations["RTV_STARTED"]="投票正在进行中!"
kShineTranslations["RTV_VOTED"] = "{TargetName} 想要发起换图投票 (还需{VotesNeeded}票才能通过)"
kShineTranslations["TOGGLE_MAP_OVERVIEW_TOOLTIP"]="显示地图总览"
kShineTranslations["SHOW_MOD_TOOLTIP"]="跳转到创意工坊"
kShineTranslations["VOTE_COUNTER"]= "{NumVotes} {NumVotes:Pluralise:vote|票}"
kShineTranslations["MAP_VOTE_MENU_SINGLE_CHOICE_DESCRIPTION"]="给你想玩的下一张地图投上一票"
kShineTranslations["NOT_ENOUGH_VOTES"]="投票数不足,换图投票失败."
kShineTranslations["MAP_VOTE_MENU_CURRENT_MAP"]= "当前地图: {MapName}"
kShineTranslations["MAP_VOTE_MENU_EXTEND_MAP"]= "延续 - {MapName}"

kShineTranslations["NOMINATE_FAIL"]= "你不能提名当前地图."
kShineTranslations["NOMINATE_DENIED"]= "已达到了允许提名次数的上限."
kShineTranslations["ALREADY_NOMINATED"]= "{MapName}已经被提名了."
kShineTranslations["NOMINATIONS_FULL"]= "提名已满."
kShineTranslations["NOMINATED_MAP"]= "{TargetName}为换图投票提名了{MapName}."
kShineTranslations["PLAYER_VOTED"]= "{TargetName}{Revote:BoolToPhrase:又投给了|投给了}{MapName}. （目前有{Votes}{Votes:Pluralise:票|票},总共有{TotalVotes}人参与了投票）"
kShineTranslations["PLAYER_VOTED_PRIVATE"]= "你{Revote:BoolToPhrase:又投给了|投给了}{MapName}. （目前有{Votes}{Votes:Pluralise:票|票},总共有{TotalVotes}人参与了投票)"
kShineTranslations["WINNER_VOTES"]= "{MapName} 以 {Votes}/{TotalVotes} 的比例赢得了投票."
kShineTranslations["EXTENDING_TIME"]= "当前地图时间延长{Duration:Duration}"

kShineTranslations["TIME_LEFT"]= "此地图还剩下{Duration:Duration}"

kShineTranslations["MAP_EXTENDED_TIME"]= "地图被{Duration:Sign:缩短|延长}了{Duration:Abs::Duration}"
kShineTranslations["VOTES_TIED"]= "票数在{MapNames}之间持平."
kShineTranslations["CHOOSING_RANDOM_MAP"]= "正在随机选择地图,系统选择了：{MapName}."
kShineTranslations["MAP_CHANGING"]= "服务器将在 {Duration:Duration} 后更换地图."

kShineTranslations["FORCED_VOTE"]= "强制开始了换图投票"
kShineTranslations["CANT_FORCE"]= "无法发起新的投票，当前已经有一项投票正在进行中"

kShineTranslations["VOTE_FAIL_MAP_CHANGE"]= "正在换图,无法发起投票."
kShineTranslations["VOTE_FAIL_INSUFFICIENT_PLAYERS"]= "所需玩家人数不足,无法发起投票."
kShineTranslations["VOTE_FAIL_TIME"]= "眼下你无法发起换图投票."
kShineTranslations["VOTE_FAIL_IN_PROGRESS"]= "一项投票已经正在进行中了."
kShineTranslations["VOTE_FAIL_ALREADY_VOTED"]= "你已经投过发起换图投票了."
kShineTranslations["VOTE_FAIL_INVALID_MAP"]= "{MapName}并不是一个有效的地图名."
kShineTranslations["VOTE_FAIL_VOTED_MAP"]= "你已经投过{MapName}的票了."

--Readyroom Queue
kShineTranslations["Ready Room"]= "[入场队列]"
kShineTranslations["QUEUE_CHANGED"]= "在你前面的玩家离开了队列. 目前的排队序号为 {Position}."
kShineTranslations["QUEUE_CHANGED_VIP"]= "一个特权玩家插队了. 目前的排队序号为 {Position}."
kShineTranslations["PIORITY_QUEUE_CHANGED"]= "A player in front of you left the reservered slot queue. You are the {Position} spectator in the reserved slot queue."
kShineTranslations["PIORITY_QUEUE_CHANGED_VIP"]= "A VIP player joined the reservered slot queue in front of you. You are the {Position} spectator in the reserved slot queue."
kShineTranslations["QUEUE_ADDED"]=  "开始排队! 当前的排队序号为 {Position}. 聊天框输入 !rr_dequeue 离开队列."
kShineTranslations["PIORITY_QUEUE_ADDED"]= "You joined the reserved slot queue! Your current position is {Position}. To leave the queue enter !rr_dequeue into the chat."
kShineTranslations["QUEUE_POSITION"]=  "当前的排队序号为 {Position}."
kShineTranslations["PIORITY_QUEUE_POSITION"]= "Your current position in the reserved slot queue is {Position}."
kShineTranslations["QUEUE_POSITION_UNKNOWN"]= "还未开始排队!"
kShineTranslations["DEQUEUE_SUCCESS"]= "停止了排队!"
kShineTranslations["QUEUE_LEAVE"]= "排队成功. 已被挪到预备室!  感谢你的耐心等待,请尽快加入游戏."
kShineTranslations["ENQUEUE_ERROR_PLAYER"]= "只有观战可以进入排队!"
kShineTranslations["QUEUE_INFORM"]= "如果你想进场游戏请按下 |F4建| 或者再聊天框输入 !rr_enqueue. 目前有 {Position} 个玩家正在排队!"
kShineTranslations["QUEUE_WELCOME_BACK"]= "欢迎回来! 你的排队序号已被复原 ({Position}). 聊天框输入 !rr_dequeue 离开队列."
kShineTranslations["QUEUE_WAITTIME"]= "当前服务器的平均排队时间为 %s. 可以考虑暖暖别的服务器."