---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/5/11 11:33
---

local localConfigPath = "config://NS2CN/LocalFile.json"

CNPersistent = { }

--Read
if GetFileExists(localConfigPath) then
    local localConfig = io.open(localConfigPath, "r")
    if localConfig then
        CNPersistent = json.decode(localConfig:read("*all"))
        io.close(localConfig)
    end
end

function CNPersistentSave()
    local savedFile = io.open(localConfigPath, "w+")
    if savedFile then
        savedFile:write(json.encode(CNPersistent, { indent = true }))
        io.close(savedFile)
    end
end