---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/2/28 15:30
---

if Client then
    ModLoader.SetupFileHook( "lua/Client.lua", "lua/CNArtRes/BadgeLocale.lua", "post" )
end

if AddHintModPanel then
    --math.randomseed(tostring(os.time()):reverse():sub(1, 6))
    --for i = 1, 100 do math.random() end

    --Shared.Message("[CNCE] Banner Welcome:" .. tostring(titleRandom))
    AddHintModPanel(PrecacheAsset(string.format("materials/CNLocalize/Banner_Welcome1.material")), "https://docs.qq.com/doc/DUFlBR0ZJeFRiRnRi","社区指南(不读让NS2CN玩家后悔终生)")
    AddHintModPanel(PrecacheAsset(string.format("materials/CNLocalize/Banner_Court.material")), "https://docs.qq.com/doc/DUFZ1aWJacU5iV3h0","NS2CN社区异闻录.")
    AddHintModPanel(PrecacheAsset(string.format("materials/CNLocalize/Banner_NS2CNTournament.material")), "https://docs.qq.com/doc/DSWR6ZnFqRnpoTkVa","原来还有不是6v6的比赛?")
    AddHintModPanel(PrecacheAsset(string.format("materials/CNLocalize/Banner_Support.material")), "https://docs.qq.com/doc/DUHhYQlhDaGFTYVZ5?u","社区可能会倒闭 但是永远不会变质")
end
