---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/2/28 15:30
---

if Client then
    Script.Load("lua/CNArtRes/BadgeLocale.lua")
end

if AddHintModPanel then
    --math.randomseed(tostring(os.time()):reverse():sub(1, 6))
    --for i = 1, 100 do math.random() end

    --Shared.Message("[CNCE] Banner Welcome:" .. tostring(titleRandom))
    AddHintModPanel(PrecacheAsset(string.format("materials/CNLocalize/Banner_Welcome1.material")), "https://docs.qq.com/doc/DUFlBR0ZJeFRiRnRi","社区指南(不读让NS2CN玩家后悔终生)")
    AddHintModPanel(PrecacheAsset(string.format("materials/CNLocalize/Banner_Court.material")), "https://docs.qq.com/doc/DUFZ1aWJacU5iV3h0","NS2CN社区异闻录,仅供娱乐,请勿当真.")
end
