---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by letsb.
--- DateTime: 2026/3/13 0:14
---
Script.Load("lua/CNBooting/ModPanelActionFinderMixin.lua")

local oldOnCreate = Player.OnCreate
function Player:OnCreate()
    oldOnCreate(self)
    InitMixin(self, ReadyRoomPlayerActionFinderMixin)
end