---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by letsb.
--- DateTime: 2025/3/15 13:17
---

RegisterVoteType("VotePracticeMode", {})
if Client then
    local function SetupVotes(voteMenu)
        AddVoteStartListener("VotePracticeMode", function(msg)
            return Locale.ResolveString("VOTE_PRACTICE_MODE_QUERY")
        end)
        voteMenu:AddMainMenuOption(Locale.ResolveString("VOTE_PRACTICE_MODE"),nil, function( msg )
            AttemptToStartVote("VotePracticeMode", { })
        end)

    end
    AddVoteSetupCallback(SetupVotes)
end

if Server then
    SetVoteSuccessfulCallback("VotePracticeMode", 1, function( msg )
        local enable = not Shared.GetCheatsEnabled()
        if enable then
            Shared.ConsoleCommand("cheats 1")
            Shared.ConsoleCommand("sh_maxbots 0 false")
        else
            Shared.ConsoleCommand("sh_maxbots 16 true")
        end
        if Shine then
            Shine:NotifyDualColour( nil, 235, 152, 78 ,"[提示]",255, 255, 255,
                    string.format("服务器已切换为[%s]",enabled and "练习模式" or "正常模式"))
        end
    end)
end 