---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/2/6 2:37
---
function CreateVoiceMessage(player, voiceId)
    --FIXME bigmac (need to use enum)
    local client = player:GetClient()

    if client and player.OnTaunt and (voiceId == kVoiceId.MarineTaunt or voiceId == kVoiceId.AlienTaunt) then
        player:OnTaunt()
    end

    --  Respect special reinforced reward VO
    if voiceId == kVoiceId.MarineTaunt and GetHasDLC(kShadowProductId, client) then
        voiceId = kVoiceId.MarineTauntExclusive
    end
    ----------
    local soundData = GetAdditionalVoiceSoundData(voiceId) or GetVoiceSoundData(voiceId)
    ------------
    if soundData then

        local soundName = soundData.Sound

        if HasMixin(player, "MarineVariant") and player:GetMarineType() == kMarineVariantsBaseType.female and soundData.SoundFemale ~= nil then
            soundName = soundData.SoundFemale
        end

        if soundData.Function then
            soundName = soundData.Function(player) or soundName
        end

        -- the request sounds always play for everyone since its something the player is doing actively
        -- the auto voice overs are triggered somewhere else server side and play for team only
        if soundName then
            StartSoundEffectOnEntity(soundName, player)
        end

        local team = player:GetTeam()
        if team then

            -- send alert so a marine commander for example gets notified about players who need a medpack / ammo etc.
            if not GetIsPointInGorgeTunnel(player:GetOrigin()) and soundData.AlertTechId and soundData.AlertTechId ~= kTechId.None then
                team:TriggerAlert(soundData.AlertTechId, player)
            end

        end

    end

end